#Project Information
site_name: ABAP For HANA
site_description: Treinamento de ABAP For HANA
site_author: Matheus Goulart

#Repository
repo_url: https://github.com/matheusog/treinamento.ABAPForHANA.git

#Customization
extra_css: 
  - css/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.def_list

#Page Tree
pages: 
  - Home: 'index.md'
  - Pré-Requisitos: 'PreRequisitos/preRequisitos.md' 
  - Modelo de Dados: 'FlightDataModel/flightModel.md'
  - Eclipse:
    - Exercício 1: 'ExerciciosEclipse/Exer_1/exercicio1.md'
    - Exercício 2: 'ExerciciosEclipse/Exer_2/exercicio2.md'
  - HANA:
    - Exercício 1: 'ExerciciosHANA/Exer_1/exercicio1.md'
    - Exercício 2: 'ExerciciosHANA/Exer_2/exercicio2.md'
    - Exercício 3: 'ExerciciosHANA/Exer_3/exercicio3.md'
    - Exercício 4: 'ExerciciosHANA/Exer_4/exercicio4.md'
    - Exercício 5: 'ExerciciosHANA/Exer_5/exercicio5.md'
    - Exercício 6: 'ExerciciosHANA/Exer_6/exercicio6.md'
    - Exercício 7: 'ExerciciosHANA/Exer_7/exercicio7.md'
    - Exercício 8: 'ExerciciosHANA/Exer_8/exercicio8.md'
    - Exercício 9: 'ExerciciosHANA/Exer_9/exercicio9.md'
    - Exercício 10: 'ExerciciosHANA/Exer_10/exercicio10.md'
  - ABAP: 
    - Pacote: 'ExerciciosABAP/Exer_1/exercicio1.md'
    - Exercício 1: 'ExerciciosABAP/Exer_1_B/exercicio1_b.md'
    - Exercício 2: 'ExerciciosABAP/Exer_2/exercicio2.md'
    - Exercício 3: 'ExerciciosABAP/Exer_3/exercicio3.md'
    - Exercício 4: 'ExerciciosABAP/Exer_4/exercicio4.md'
    - Exercício 5: 'ExerciciosABAP/Exer_5/exercicio5.md'
    - Exercício 6: 'ExerciciosABAP/Exer_6/exercicio6.md'
    - Exercício 7: 'ExerciciosABAP/Exer_7/exercicio7.md'